import Head from "next/head"
import CartProduct from "../../components/cart/Cart"

const Cart = () => {

  return (
    <>
      <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/cob-logo.webp" />
      </Head>
      <CartProduct/>
    </>
  )
}

export default Cart
