version: "3.7"

services: 
    web:
      image: nginx:1.13.0-alpine
      container_name: wrk-nginx
      restart: always
      ports: 
      - 9001:80
      volumes: 
      - ./out/:/usr/share/nginx/html