import Head from "next/head"
import { useRouter } from "next/router"
import { useState } from "react"
import { useEffect } from "react"
import { Spinner } from "react-bootstrap"
import ProductDetail from "../../components/product_detail/ProductDetail"
import { product } from "../../model/mock"

const ProDuctDetail = () => {
  const router = useRouter()
  const [data, setData] = useState(null)
  const [isLoading, setIsLoading] = useState(true)
  useEffect(() => {
    if (router.query.id) {
      console.log(data);
      setData(product.find(prd => prd.attributes.id === Number(router.query.id)))
      setIsLoading(false)
    }
  }, [router.query.id])

  return (
    <>
      <Head>
        <title>Product detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/cob-logo.webp" />
      </Head>

      {(() => {
        if (isLoading) {
          return (
            <div
              style={{
                display: "flex",
                justifyContent: "center",
                marginTop: "50px",
              }}
            >
              <Spinner animation="border" />
            </div>
          )
        } else {
          return <ProductDetail product={data} />
        }
      })()}
    </>
  )
}

export default ProDuctDetail
